require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1
  Exclude:
    - 'Rakefile'

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 190

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 8

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

FormatString:
  EnforcedStyle: percent

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Layout/RescueEnsureAlignment:
  Enabled: false